name = "CompactTranslatesDict"
uuid = "455b6770-8cd4-11e8-0457-dd6f5558b097"
version = "0.2.2"

[deps]
BasisFunctions = "4343a256-5453-507d-8aad-01a9d7189916"
CardinalBSplines = "87d49508-7ad8-11e8-0eda-cb6920b58870"
DomainIntegrals = "cc6bae93-f070-4015-88fd-838f9505a86c"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GridArrays = "356ae075-8bc9-5ef9-a342-46c9ba26438c"
InfiniteVectors = "a3035606-0d97-52a5-9f37-19f5f67b7424"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BasisFunctions = "0.3.1"
CardinalBSplines = "0.2"
DomainIntegrals = "0.3"
DomainSets = "0.4"
FillArrays = "0.10,0.11"
GridArrays = "0.1.8"
InfiniteVectors = "0.1"
Reexport = "1.0"
julia = "1.5"

[targets]
test = ["Test"]
